### ISSUE TITLE
Shamelessly recommend my own English practicing Chome extension

### ISSUE THREAD

**Issue by Shawn91** [interaminense/learning-english#24]
Hi. I just stumbled upon your repository and found a lot of useful resources.

I'd like to recommend a Chrome extension made by myself called [Pact English](https://chromewebstore.google.com/detail/pact-english/cajdgbcnafdfgmnignadekjeofblcmio?hl=en&pli=1). It helps users practice English while watching Youtube videos by turning some subtitles into dictation or fill-in-the-blank practices.

Not so sure whether it is good enough to make it onto your repository list. But I think it is an interesting way of practicing English.

The product is completely free currently.

website: https://painlessenglish.com/

chrome extension page: https://chromewebstore.google.com/detail/pact-english/cajdgbcnafdfgmnignadekjeofblcmio?hl=en&pli=1

**Comment by interaminense** [comment]
Hi @Shawn91, I added your suggestion in our repo. Thanks a lot! 06b0a5b94aa4e7ae08fea2113f3e58d7914db806
